UI/WebStore/Components/BreadCrumbsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using WebStore.Controllers;
using WebStore.Domain.ViewModels;
using WebStore.Infrastructure.Interfaces;

namespace WebStore.Components
{
    public class BreadCrumbsViewComponent : ViewComponent
    {
        private readonly IProductData _ProductData;

        public BreadCrumbsViewComponent(IProductData ProductData) => _ProductData = ProductData;

        private void GetParameters(out BreadCrumbType Type, out int id, out BreadCrumbType FromType)
        {
            Type = Request.Query.ContainsKey("SectionId") ? BreadCrumbType.Section 
                : Request.Query.ContainsKey("BrandId") ? BreadCrumbType.Brand : BreadCrumbType.None;

            if ((string)ViewContext.RouteData.Values["action"] == nameof(CatalogController.Details))
                Type = BreadCrumbType.Product;

            id = 0;

            FromType = BreadCrumbType.Section;

            // Define parameter id
            switch(Type)
            {
                default: throw new ArgumentOutOfRangeException(nameof(Type), Type, null);
                case BreadCrumbType.None: 
                    break;

                case BreadCrumbType.Section:
                    id = int.Parse(Request.Query["SectionId"].ToString());
                    break;

                case BreadCrumbType.Brand:
                    id = int.Parse(Request.Query["BrandId"].ToString());
                    break;
                case BreadCrumbType.Product:
                    id = int.Parse(ViewContext.RouteData.Values["id"].ToString() ?? string.Empty);
                    // FromBrand - attribute from first item in the features_items list on _FeaturesItems Partial View
                    if (Request.Query.ContainsKey("FromBrand"))
                        FromType = BreadCrumbType.Brand;
                    break;
            }
        }

        public IViewComponentResult Invoke()
        {
            GetParameters(out var type, out var id, out var from_type);

            switch (type)
            {
                default: return View(Array.Empty<BreadCrumbsViewModel>());

                case BreadCrumbType.Section:
                    return View(new[]
                    {
                    new BreadCrumbsViewModel
                    {
                        BreadCrumbType = BreadCrumbType.Section,
                        Id = id,
                        Name = _ProductData.GetSectionById(id).Name
                    },
                    });
                case BreadCrumbType.Brand:
                    return View(new[]
                    {
                    new BreadCrumbsViewModel
                    {
                        BreadCrumbType = BreadCrumbType.Brand,
                        Id = id,
                        Name = _ProductData.GetBrandById(id).Name
                    },
                    });
                case BreadCrumbType.Product:
                    var product = _ProductData.GetProductById(id);
                    return View(new[]
                    {
                        new BreadCrumbsViewModel
                        {
                            BreadCrumbType = from_type,
                            Id = from_type == BreadCrumbType.Section ? product.Section.Id : product.Brand.Id,
                            Name = from_type == BreadCrumbType.Section ? product.Section.Name : product.Brand.Name
                        },
                        new BreadCrumbsViewModel
                        {
                            BreadCrumbType = BreadCrumbType.Product,
                            Id = product.Id,
                            Name = product.Name
                        },
                    });
            }
        }
    }
}

UI/WebStore/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Collections.Generic;
using System.Linq;
using WebStore.Domain.DTO.Products;
using WebStore.Domain.Entities;
using WebStore.Domain.ViewModels;
using WebStore.Infrastructure.Interfaces;
using WebStore.Infrastructure.Mapping;

namespace WebStore.Controllers
{
    public class CatalogController : Controller
    {
        private const string __PageSize = "PageSize";

        private readonly IProductData _ProductData;
        private readonly IConfiguration _Configuration;

        public CatalogController(IProductData ProductData, IConfiguration Configuration)
        {
            _ProductData = ProductData;
            _Configuration = Configuration;
        }

        public IActionResult Shop(int? SectionId, int? BrandId, int Page = 1)
        {
            var page_size = int.TryParse(_Configuration["PageSize"], out var size) ? size : (int?)null;

            var filter = new ProductFilter
            {
                SectionId = SectionId,
                BrandId = BrandId,
                Page = Page,
                PageSize = page_size
            };
            var products = _ProductData.GetProducts(filter);

            return View(new CatalogViewModel
            {
                SectionId = SectionId,
                BrandId = BrandId,
                Products = products.Products.Select(ProductMapping.FromDTO).Select(ProductMapping.ToView).OrderBy(p => p.Order),
                PageViewModel = new PageViewModel
                {
                    PageSize = page_size ?? 0,
                    PageNumber = Page,
                    TotalItems = products.TotalCount
                }
            });
        }

        public IActionResult Details(int id)
        {
            var product = _ProductData.GetProductById(id);

            if (product is null)
                return NotFound();

            return View(product.FromDTO().ToView());
        }

        #region API

        public IActionResult GetFilteredItems(int? SectionId, int? BrandId, int Page)
        {
            var products = GetProducts(SectionId, BrandId, Page)
                .Select(ProductMapping.FromDTO)
                .Select(ProductMapping.ToView)
                .OrderBy(p => p.Order);

            return PartialView("Partial/_FeaturesItems", products);
        }

        private IEnumerable<ProductDTO> GetProducts(int? SectionId, int? BrandId, int Page) =>
            _ProductData.GetProducts(new ProductFilter
            {
                SectionId = SectionId,
                BrandId = BrandId,
                Page = Page,
                PageSize = int.Parse(_Configuration[__PageSize])
            }).Products;

        #endregion
    }
}

UI/WebStore/Views/Catalog/Details.cshtml
@model WebStore.Domain.ViewModels.ProductViewModel
@{
    ViewData["Title"] = $"Товар {Model.Name}";
}

    <div class="container">
        <vc:bread-crumbs />
    </div>

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <partial name="Partial/_LeftSideBar" />
            </div>

            <div class="col-sm-9 padding-right">
                <div class="product-details">
                    <!--product-details-->
                    <div class="col-sm-5">
                        <div class="view-product">
                            <img src="~/images/product-details/1.jpg" alt="" />
                            <h3>ZOOM</h3>
                        </div>
                        <div id="similar-product" class="carousel slide" data-ride="carousel">

                            <!-- Wrapper for slides -->
                            <div class="carousel-inner">
                                <div class="item active">
                                    <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                                    <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                                    <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                                </div>
                                <div class="item">
                                    <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                                    <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                                    <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                                </div>
                                <div class="item">
                                    <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                                    <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                                    <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                                </div>

                            </div>

                            <!-- Controls -->
                            <a class="left item-control" href="#similar-product" data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                            </a>
                            <a class="right item-control" href="#similar-product" data-slide="next">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>

                    </div>
                    <div class="col-sm-7">
                        <div class="product-information">
                            <!--/product-information-->
                            <img src="~/images/shop/@Model.ImageUrl" class="newarrival" alt="" />
                            <h2>@Model.Name</h2>
                            <p>арт.: @Model.Id.ToString("0000000")</p>
                            <img src="~/images/product-details/rating.png" alt="" />
                            <span>
                                <span>@Model.Price.ToString("C")</span>
                                <label>Количество:</label>
                                <input type="text" value="3" />
                                <a asp-controller="Cart" asp-action="AddToCart" asp-route-id="@Model.Id" data-id="@Model.Id" class="btn btn-default cart add-to-cart">
                                    <i class="fa fa-shopping-cart"></i>
                                    Добавить в корзину
                                </a>
                            </span>
                            <p><b>Availability:</b> In Stock</p>
                            <p><b>Condition:</b> New</p>
                            <p><b>Бренд:</b> @Model.Brand</p>
                            <a href=""><img src="~/images/product-details/share.png" class="share img-responsive" alt="" /></a>
                        </div><!--/product-information-->
                    </div>
                </div><!--/product-details-->
            </div>
        </div>
    </div>
</section>

UI/WebStore/Views/Catalog/Shop.cshtml
@model WebStore.Domain.ViewModels.CatalogViewModel

    <div class="container">
        <vc:bread-crumbs />
    </div>

<section id="advertisement">
    <div class="container">
        <img src="~/images/shop/advertisement.jpg" alt="" />
    </div>
</section>

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <partial name="Partial/_LeftSideBar" />
            </div>

            <div class="col-sm-9 padding-right">
                <div id="catalog-items-container">
                    <partial name="Partial/_FeaturesItems" model="@Model.Products" />
                </div>

                <paging page-model="@Model.PageViewModel" page-action="Shop" page-url-SectionId="@Model.SectionId" page-url-BrandId="@Model.BrandId">
                </paging>
            </div>
        </div>
    </div>
</section>

@section Scripts{ 
<script src="~/lib/jquery-loading-overlay/loadingoverlay.min.js"></script>
<script src="~/js/Shop/CatalogLogic.js" asp-append-version="true"></script>
<script>
    $(function () {
        Catalog.init({
            getUrl: "@Url.Action("GetFilteredItems", "Catalog")"
        });
    });
</script>
}